---
swagger: "2.0"
info:
  description: "BUMN"
  version: "1.0.0"
  title: "BUMN"
host: "virtserver.swaggerhub.com"
basePath: "/Dev87/Reusable_API/1.0.0"
schemes:
- "https"
- "http"
paths:
  /list-bumn:
    get:
      summary: "/list-bumn?appId={nama project}"
      description: "list BUMN"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/listbumn"
  /category-bumn:
    get:
      summary: "/category-bumn?appId={nama project}"
      description: "category BUMN\n"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/categorybumn"
  /profile:
    get:
      summary: "/profile?page={nomor halaman}&count={jumlah data}&bumnId={bumnId}&appId={nama\
        \ project}"
      description: "profile"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "page"
        in: "query"
        description: "number of page"
        required: true
        type: "string"
      - name: "count"
        in: "query"
        description: ""
        required: true
        type: "string"
      - name: "bumnId"
        in: "query"
        description: "Id of BUMN"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/profiles"
    post:
      summary: "/profile?appId={nama project}"
      description: "post profile"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "query"
        description: ""
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/postuser"
  /bumn/{bumnId}:
    get:
      summary: "/bumn/{bumnId}?appId={nama project}"
      description: "get bumn by id"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "bumnId"
        in: "path"
        description: "id of BUMN"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/bumnid"
  /list-bumn/{categoryId}:
    get:
      summary: "/list-bumn/{categoryId}?appId={nama project}"
      description: "get list bumn by category id"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "categoryId"
        in: "path"
        description: "id of category"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/list-bumn"
  /profile/{userId}:
    get:
      summary: "/profile/{userId}?appId={nama project}"
      description: "get profile by user id"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        description: "id of user"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/profile"
  /user:
    get:
      summary: "/user?bumnId={bumnId}&nik={nik}&appId={nama project}"
      description: "get user by bumnId and nik"
      consumes:
      - "application/json"
      produces:
      - "appliaction/json"
      parameters:
      - name: "bumnId"
        in: "query"
        description: "id of bumn"
        required: true
        type: "string"
      - name: "nik"
        in: "query"
        description: "nomor induk karyawan"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/user"
  /summary-detail:
    get:
      summary: "/summary-detail?appId={nama project}"
      description: "summary detail"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/summarydetail"
  /summary-bumn:
    get:
      summary: "/summary-bumn?appId={nama project}"
      description: "summary bumn"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/summarybumn"
definitions:
  listbumn:
    properties:
      status:
        type: "string"
        example: "success"
      data:
        $ref: "#/definitions/listbumn_data"
      code:
        type: "integer"
        example: 200
      message:
        type: "string"
        example: "Get List BUMN"
    example:
      code: 200
      data:
        bumnName: "Kementerian BUMN"
        bumnId: 0
        imageUrl: "https://s3-ap-southeast-1.amazonaws.com/sobatbumn/logo/000.png"
        _id: "5a372002b47a451a843f286a"
        categoryId: 14
      message: "Get List BUMN"
      status: "success"
  categorybumn:
    properties:
      status:
        type: "string"
        example: "success"
      data:
        $ref: "#/definitions/categorybumn_data"
      code:
        type: "integer"
        example: 200
      message:
        type: "string"
        example: "Get List BUMN"
    example:
      code: 200
      data:
        _id: "5a3722636f283c1c5305fe4b"
        categoryName: "Telekomunikasi"
        categoryId: 1
      message: "Get List BUMN"
      status: "success"
  summarydetail:
    properties:
      status:
        type: "string"
        example: "success"
      data:
        type: "array"
        items:
          $ref: "#/definitions/data2"
      code:
        type: "integer"
        example: 200
      message:
        type: "string"
        example: "Get User Summary"
    example:
      code: 200
      data:
      - bumnName: "PT Bank Mandiri (Persero) Tbk."
        bumnId: 8
        images: "https://s3-ap-southeast-1.amazonaws.com/sobatbumn/logo/008.png"
        count: 38413
      - bumnName: "PT Bank Mandiri (Persero) Tbk."
        bumnId: 8
        images: "https://s3-ap-southeast-1.amazonaws.com/sobatbumn/logo/008.png"
        count: 38413
      message: "Get User Summary"
      status: "success"
  data2:
    type: "object"
    properties:
      bumnId:
        type: "integer"
        example: 8
      count:
        type: "integer"
        example: 38413
      bumnName:
        type: "string"
        example: "PT Bank Mandiri (Persero) Tbk."
      images:
        type: "string"
        example: "https://s3-ap-southeast-1.amazonaws.com/sobatbumn/logo/008.png"
    example:
      bumnName: "PT Bank Mandiri (Persero) Tbk."
      bumnId: 8
      images: "https://s3-ap-southeast-1.amazonaws.com/sobatbumn/logo/008.png"
      count: 38413
  profiles:
    type: "object"
    properties:
      status:
        type: "string"
        example: "success"
      data:
        $ref: "#/definitions/data3"
      meta:
        $ref: "#/definitions/meta"
      code:
        type: "integer"
        example: 200
      message:
        type: "string"
        example: "Get Profile"
    example:
      code: 200
      data:
        code: 200
        err: "null"
        data:
        - bumnName: "PT Telekomunikasi Indonesia (Persero) Tbk"
          nik: 592115
          profilePicture: "https://s3-ap-southeast-1.amazonaws.com/sobatbumn/user/default_profile_picture.jpeg"
          bumnId: 111
          mobilePhone: 81322940010
          isVerified: "true"
          name: "Ketut Darsumantra"
          _id: "5a39ba655fdb1b077ff9af71"
          loginStatus: "false"
          userId: "02048eb4-1639-4f8c-8891-9bca33700316"
          email: "592115@telkom.co.id"
        - bumnName: "PT Telekomunikasi Indonesia (Persero) Tbk"
          nik: 592115
          profilePicture: "https://s3-ap-southeast-1.amazonaws.com/sobatbumn/user/default_profile_picture.jpeg"
          bumnId: 111
          mobilePhone: 81322940010
          isVerified: "true"
          name: "Ketut Darsumantra"
          _id: "5a39ba655fdb1b077ff9af71"
          loginStatus: "false"
          userId: "02048eb4-1639-4f8c-8891-9bca33700316"
          email: "592115@telkom.co.id"
        message: "null"
      meta:
        totalPage: 1479
        limit: 10
        page: 1
        totalRecord: 14782
      message: "Get Profile"
      status: "success"
  data3:
    type: "object"
    properties:
      err:
        type: "string"
        example: "null"
      data:
        type: "array"
        items:
          $ref: "#/definitions/data5"
      code:
        type: "integer"
        example: 200
      message:
        type: "string"
        example: "null"
    example:
      code: 200
      err: "null"
      data:
      - bumnName: "PT Telekomunikasi Indonesia (Persero) Tbk"
        nik: 592115
        profilePicture: "https://s3-ap-southeast-1.amazonaws.com/sobatbumn/user/default_profile_picture.jpeg"
        bumnId: 111
        mobilePhone: 81322940010
        isVerified: "true"
        name: "Ketut Darsumantra"
        _id: "5a39ba655fdb1b077ff9af71"
        loginStatus: "false"
        userId: "02048eb4-1639-4f8c-8891-9bca33700316"
        email: "592115@telkom.co.id"
      - bumnName: "PT Telekomunikasi Indonesia (Persero) Tbk"
        nik: 592115
        profilePicture: "https://s3-ap-southeast-1.amazonaws.com/sobatbumn/user/default_profile_picture.jpeg"
        bumnId: 111
        mobilePhone: 81322940010
        isVerified: "true"
        name: "Ketut Darsumantra"
        _id: "5a39ba655fdb1b077ff9af71"
        loginStatus: "false"
        userId: "02048eb4-1639-4f8c-8891-9bca33700316"
        email: "592115@telkom.co.id"
      message: "null"
  meta:
    type: "object"
    properties:
      page:
        type: "integer"
        example: 1
      limit:
        type: "integer"
        example: 10
      totalPage:
        type: "integer"
        example: 1479
      totalRecord:
        type: "integer"
        example: 14782
    example:
      totalPage: 1479
      limit: 10
      page: 1
      totalRecord: 14782
  data5:
    type: "object"
    properties:
      _id:
        type: "string"
        format: "uuid"
        example: "5a39ba655fdb1b077ff9af71"
      nik:
        type: "integer"
        format: "int64"
        example: 592115
      profilePicture:
        type: "string"
        example: "https://s3-ap-southeast-1.amazonaws.com/sobatbumn/user/default_profile_picture.jpeg"
      name:
        type: "string"
        example: "Ketut Darsumantra"
      userId:
        type: "string"
        format: "uuid"
        example: "02048eb4-1639-4f8c-8891-9bca33700316"
      mobilePhone:
        type: "integer"
        example: 81322940010
      bumnName:
        type: "string"
        example: "PT Telekomunikasi Indonesia (Persero) Tbk"
      loginStatus:
        type: "string"
        example: "false"
      email:
        type: "string"
        example: "592115@telkom.co.id"
      isVerified:
        type: "string"
        example: "true"
      bumnId:
        type: "integer"
        format: "int32"
        example: 111
    example:
      bumnName: "PT Telekomunikasi Indonesia (Persero) Tbk"
      nik: 592115
      profilePicture: "https://s3-ap-southeast-1.amazonaws.com/sobatbumn/user/default_profile_picture.jpeg"
      bumnId: 111
      mobilePhone: 81322940010
      isVerified: "true"
      name: "Ketut Darsumantra"
      _id: "5a39ba655fdb1b077ff9af71"
      loginStatus: "false"
      userId: "02048eb4-1639-4f8c-8891-9bca33700316"
      email: "592115@telkom.co.id"
  bumnid:
    type: "object"
    properties:
      status:
        type: "string"
        example: "success"
      data:
        $ref: "#/definitions/databumn"
      code:
        type: "integer"
        format: "int32"
        example: 200
      mesaage:
        type: "string"
        example: "Get BUMN by ID"
    example:
      code: 200
      data:
        bumnName: "PT Aneka Tambang (Persero) Tbk"
        bumnid: 4
        imageUrl: "https://s3-ap-southeast-1.amazonaws.com/sobatbumn/logo/004.png"
        _id: "5a372002b47a451a843f2867"
        categoryId: 11
      mesaage: "Get BUMN by ID"
      status: "success"
  databumn:
    type: "object"
    properties:
      _id:
        type: "string"
        format: "uuid"
        example: "5a372002b47a451a843f2867"
      bumnid:
        type: "integer"
        format: "int32"
        example: 4
      bumnName:
        type: "string"
        example: "PT Aneka Tambang (Persero) Tbk"
      categoryId:
        type: "integer"
        format: "int32"
        example: 11
      imageUrl:
        type: "string"
        example: "https://s3-ap-southeast-1.amazonaws.com/sobatbumn/logo/004.png"
    example:
      bumnName: "PT Aneka Tambang (Persero) Tbk"
      bumnid: 4
      imageUrl: "https://s3-ap-southeast-1.amazonaws.com/sobatbumn/logo/004.png"
      _id: "5a372002b47a451a843f2867"
      categoryId: 11
  list-bumn:
    type: "object"
    properties:
      status:
        type: "string"
        example: "success"
      data:
        type: "array"
        items:
          $ref: "#/definitions/databumn"
      code:
        type: "integer"
        format: "int32"
        example: 200
      message:
        type: "string"
        example: "Get list BUMN By Cat ID"
    example:
      code: 200
      data:
      - bumnName: "PT Aneka Tambang (Persero) Tbk"
        bumnid: 4
        imageUrl: "https://s3-ap-southeast-1.amazonaws.com/sobatbumn/logo/004.png"
        _id: "5a372002b47a451a843f2867"
        categoryId: 11
      - bumnName: "PT Aneka Tambang (Persero) Tbk"
        bumnid: 4
        imageUrl: "https://s3-ap-southeast-1.amazonaws.com/sobatbumn/logo/004.png"
        _id: "5a372002b47a451a843f2867"
        categoryId: 11
      message: "Get list BUMN By Cat ID"
      status: "success"
  profile:
    type: "object"
    properties:
      status:
        type: "string"
        example: "success"
      data:
        $ref: "#/definitions/data"
      code:
        type: "integer"
        format: "int32"
        example: 200
      message:
        type: "string"
        example: "Get Profile"
    example:
      code: 200
      data:
        bumnName: "BANK RAKYAT INDONESIA (PERSERO)"
        profilePicture: "https://s3-ap-southeast-1.amazonaws.com/sobatbumn/user/default_profile_picture.jpeg"
        nik: 1
        bumnId: 2
        mobilePhone: "08158565656"
        name: "Suprajarto"
        email: ""
      message: "Get Profile"
      status: "success"
  data:
    type: "object"
    properties:
      profilePicture:
        type: "string"
        example: "https://s3-ap-southeast-1.amazonaws.com/sobatbumn/user/default_profile_picture.jpeg"
      name:
        type: "string"
        example: "Suprajarto"
      mobilePhone:
        type: "string"
        example: "08158565656"
      email:
        type: "string"
        example: ""
      nik:
        type: "integer"
        format: "int32"
        example: 1
      bumnName:
        type: "string"
        example: "BANK RAKYAT INDONESIA (PERSERO)"
      bumnId:
        type: "integer"
        format: "int32"
        example: 2
    example:
      bumnName: "BANK RAKYAT INDONESIA (PERSERO)"
      profilePicture: "https://s3-ap-southeast-1.amazonaws.com/sobatbumn/user/default_profile_picture.jpeg"
      nik: 1
      bumnId: 2
      mobilePhone: "08158565656"
      name: "Suprajarto"
      email: ""
  user:
    type: "object"
    properties:
      status:
        type: "string"
        example: "success"
      data:
        $ref: "#/definitions/data1"
      code:
        type: "integer"
        format: "int32"
        example: 200
      message:
        type: "string"
        example: "Get user summary"
  data1:
    type: "object"
    properties:
      userId:
        type: "string"
        format: "uuid"
        example: "53bf37a9-ec39-4fcf-b5dc-db9d8108fede"
      profilePicture:
        type: "string"
        example: "https://s3-ap-southeast-1.amazonaws.com/sobatbumn/user/1560232d-55cd-4101-ad65-824846a51d70.png"
      name:
        type: "string"
        example: "ARI KURNIAWAN, ST"
      mobilePhone:
        type: "string"
        example: "081219527576"
      email:
        type: "string"
        example: "740059@telkom.co.id"
      nik:
        type: "string"
        example: "740059"
      loginStatus:
        type: "boolean"
        example: false
      bumnId:
        type: "integer"
        format: "int32"
        example: 111
      bumnName:
        type: "string"
        example: "PT Telekomunikasi Indonesia (Persero) Tbk"
  summarybumn:
    type: "object"
    properties:
      status:
        type: "string"
        example: "success"
      data:
        $ref: "#/definitions/summarybumn_data"
      code:
        type: "integer"
        format: "int32"
        example: 200
      message:
        type: "string"
        example: "Get user summary"
    example:
      code: 200
      data:
        countBumn: 121
      message: "Get user summary"
      status: "success"
  postuser:
    type: "object"
    properties:
      status:
        type: "string"
        example: "successs"
      data:
        type: "array"
        items:
          $ref: "#/definitions/data4"
      code:
        type: "integer"
        example: 200
      message:
        type: "string"
        example: "Get profile"
    example:
      code: 200
      data:
      - bumnName: "BANK MANDIRI"
        nik: "0379194772"
        profilePicture: "https://s3-ap-southeast-1.amazonaws.com/sobatbumn/user/default_profile_picture.jpeg"
        bumnId: 8
        mobilePhone: "082136398500"
        name: "LACHRIMA PARAMITA RICHY"
        _id: "5a39b76c5fdb1b07784b71b0"
        userId: "83724618-3c71-4581-a3b8-aa9b7505c7a4"
        email: ""
      - bumnName: "BANK MANDIRI"
        nik: "0379194772"
        profilePicture: "https://s3-ap-southeast-1.amazonaws.com/sobatbumn/user/default_profile_picture.jpeg"
        bumnId: 8
        mobilePhone: "082136398500"
        name: "LACHRIMA PARAMITA RICHY"
        _id: "5a39b76c5fdb1b07784b71b0"
        userId: "83724618-3c71-4581-a3b8-aa9b7505c7a4"
        email: ""
      message: "Get profile"
      status: "successs"
  data4:
    type: "object"
    properties:
      _id:
        type: "string"
        format: "uuid"
        example: "5a39b76c5fdb1b07784b71b0"
      nik:
        type: "string"
        example: "0379194772"
      profilePicture:
        type: "string"
        example: "https://s3-ap-southeast-1.amazonaws.com/sobatbumn/user/default_profile_picture.jpeg"
      name:
        type: "string"
        example: "LACHRIMA PARAMITA RICHY"
      userId:
        type: "string"
        format: "uuid"
        example: "83724618-3c71-4581-a3b8-aa9b7505c7a4"
      mobilePhone:
        type: "string"
        example: "082136398500"
      bumnName:
        type: "string"
        example: "BANK MANDIRI"
      email:
        type: "string"
        example: ""
      bumnId:
        type: "integer"
        example: 8
    example:
      bumnName: "BANK MANDIRI"
      nik: "0379194772"
      profilePicture: "https://s3-ap-southeast-1.amazonaws.com/sobatbumn/user/default_profile_picture.jpeg"
      bumnId: 8
      mobilePhone: "082136398500"
      name: "LACHRIMA PARAMITA RICHY"
      _id: "5a39b76c5fdb1b07784b71b0"
      userId: "83724618-3c71-4581-a3b8-aa9b7505c7a4"
      email: ""
  listbumn_data:
    properties:
      _id:
        type: "string"
        format: "uuid"
        example: "5a372002b47a451a843f286a"
      bumnId:
        type: "integer"
        example: 0
      bumnName:
        type: "string"
        example: "Kementerian BUMN"
      categoryId:
        type: "integer"
        example: 14
      imageUrl:
        type: "string"
        example: "https://s3-ap-southeast-1.amazonaws.com/sobatbumn/logo/000.png"
    example:
      bumnName: "Kementerian BUMN"
      bumnId: 0
      imageUrl: "https://s3-ap-southeast-1.amazonaws.com/sobatbumn/logo/000.png"
      _id: "5a372002b47a451a843f286a"
      categoryId: 14
  categorybumn_data:
    properties:
      _id:
        type: "string"
        format: "uuid"
        example: "5a3722636f283c1c5305fe4b"
      categoryName:
        type: "string"
        example: "Telekomunikasi"
      categoryId:
        type: "integer"
        example: 1
    example:
      _id: "5a3722636f283c1c5305fe4b"
      categoryName: "Telekomunikasi"
      categoryId: 1
  summarybumn_data:
    properties:
      countBumn:
        type: "integer"
        format: "int32"
        example: 121
    example:
      countBumn: 121
